# This is a basic workflow to help you get started with Actions

name: Cleanup old release and tags

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Delete Older Releases and Tags Updated
        uses: jay2610/delete-older-releases@1.4.0
        with:
          keep_latest: 5
          delete_tags: true
          delete_type: 'release'
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
