name: Release Workflow with pack squash

# Controls when the workflow will run
on:
  #  # Triggers the workflow on push or pull request events but only for the "master" branch
  #  push:
  #    branches: [ "master" ]
  #  pull_request:
  #    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  packsquash:
    name: Optimize resource pack
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Settup Discord Webhook
        id: webhook
        run: echo "WEBHOOK=${{secrets.WEBHOOK}}" >> $GITHUB_ENV
      
      - name: Get current date
        id: tag
        run: echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set release name
        run: echo "RELEASE_NAME=HBCubemonde_${{env.date}}" >> $GITHUB_ENV

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            # Optimize the pack in the root repository directory.
            # This is the default value for pack_directory when no PackSquash options are defined
            pack_directory = '.'

            # Set a custom output file path to work with the generated ZIP file
            # without needing to download its artifact in a separate step
            output_file_path = "/tmp/${{env.RELEASE_NAME}}.zip"
            
            allow_mods = ['OptiFine']
            
            # prettify shaders
            ['**/*?.{fsh,vsh,glsl}']
            shader_source_transformation_strategy = 'keep_as_is'
            
            # Temporary removing .properties processing because of accentued character encoding
            ['**/?*.properties']
            minify_properties = false
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.date}}
          name: ${{env.RELEASE_NAME}}
          files: /tmp/${{env.RELEASE_NAME}}.zip
      
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: curl samère
        id: curl
        run: |
          curl -s "${{ steps.get_current_release.outputs.assets_url }}" | grep browser_download_url | cut -d '"' -f 4 >> $GITHUB_OUTPUT


      #- name: Get download URL
      #  id: test
      #  run: TEST = curl -s "${{ steps.get_current_release.outputs.assets_url }}" | grep browser_download_url | cut -d '"' -f 4 >>
          
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ env.WEBHOOK }}
          DISCORD_USERNAME: "Dakal Itorasch"
          DISCORD_AVATAR: "https://i.imgur.com/ypTB2e8.png"
        uses: Ilshidur/action-discord@master
        with:
          args: "HELLO EVERYONE IM DAKAL AND HERE IS MY RELEASE: \n ${{ steps.curl }}"
          
