# This is a basic workflow to help you get started with Actions

name: Release Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository on master branch
      - uses: actions/checkout@master
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Get current date
        id: tag
        run: echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
      - name: Set release name
        run: echo "RELEASE_NAME=HBCubemonde_${{env.date}}" >> $GITHUB_ENV
    
      # Create a zip
      - name: Compress the pack as zip
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: "${{env.RELEASE_NAME}}.zip"
          exclusions: '*.git*'
      
      # Create a new release
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{env.RELEASE_NAME}}
          tag: ${{env.tag}}
          artifacts: "${{env.RELEASE_NAME}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}


